name: Deploy Step Function

on:
  push:
    paths:
      - 'step_functions/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update Step Function
        run: |
          aws stepfunctions update-state-machine \
            --state-machine-arn arn:aws:states:us-east-1:740811899782:stateMachine:learning-data-engineering \
            --definition file://step_functions/state_machine.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
