name: Deploy Glue Jobs

on:
  push:
    paths:
      - 'glue_jobs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Upload scripts to S3
        run: |
          aws s3 cp glue_jobs/ s3://learning-data-engineering-7799/glue_scripts/ --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Update all Glue Jobs
        run: |
          for file in glue_jobs/*.py; do
            job_name=$(basename "$file" .py)_pipeline
            script_name=$(basename "$file")

            echo "Updating $job_name"

            aws glue update-job --job-name $job_name \
              --job-update "{
              \"Role\": \"glue-customer-pipeline-role\",
                \"Command\": {
                  \"Name\": \"glueetl\",
                  \"ScriptLocation\": \"s3://learning-data-engineering-7799/glue_scripts/$script_name\"
                }
              }"
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
